{% set name = "bbmapy" %}
{% set version = "0.0.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bbmapy-{{ version }}.tar.gz
  sha256: 76cc3e1f07c03250104f9413d97b5c486d4dee96609eb62b65946e636e36f5fc

build:
  noarch: python
  number: 0
  script: |
    {{ PYTHON }} -m pip install . -vv
  binary_relocation: false 
  entry_points:
    - bbmapy-test=bbmapy.test:main
    - bbmapy-ensure-java-on-build=bbmapy.update:ensure_java_availability_on_build
    - bbmapy-ensure-java-on-run=bbmapy.update:ensure_java_availability_post_install
  ignore_run_exports:
    - python
    - rich
    - install-jdk
  run_exports:
    - {{ pin_subpackage("bbmapy", max_pin="x.x") }}

requirements:
  build:
    - python >=3.9
    - patchelf
    - pip
    - hatchling
  host:
    - python >=3.9
    - hatchling
    - pip
    - rich
  run:
    - python >=3.9
    - rich
    - install-jdk
test:
  imports:
    - bbmapy
  commands:
    - pip check
    - python -c "from bbmapy.update import ensure_java_availability_post_install; ensure_java_availability_post_install()"
    - bbmapy-test --help
  requires:
    - pip

about:
  home: https://github.com/urineri/bbmapy
  license: custom
  license_file: LICENSE
  summary: 'A Python wrapper for BBTools'
  description: |
    bbmapy is a Python wrapper for BBTools, a suite of bioinformatics tools.
    It provides a convenient interface to use BBTools from Python scripts.
  doc_url: https://github.com/urineri/bbmapy
  dev_url: https://github.com/urineri/bbmapy

extra:
  recipe-maintainers:
    - urineri 