{% set name = "bbmapy" %}
{% set version = "0.0.42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bbmapy-{{ version }}.tar.gz
  sha256: c5dcf50ad25056b5f324a49e68faf085286371741a24ab6d500e0ffa6b228b8e

build:
  noarch: python
  number: 0
  script:
   {{ PYTHON }} -m pip install . -vv  && {{ PYTHON }} -c "from bbmapy.update import ensure_java_availability_on_build; ensure_java_availability_on_build()"

entry_points:
  - bbmapy-test=bbmapy.test:main
  - bbmapy-ensure-java = "bbmapy.update:ensure_java_availability_on_build"

run_exports:
    - {{ pin_subpackage("bbmapy", max_pin=None) }}

requirements:
  build:
    - python >=3.9
    - pip
    - git
    - hatchling
    - wget
    - rich
    - install-jdk
  host:
    - python >=3.9
    - hatchling
    - pip
    - rich
  run:
    - python >=3.9
    - rich

test:
  imports:
    - bbmapy
  commands:
    - pip check
    - bbmapy-test --help
    - bbmapy-ensure-java --help
  requires:
    - pip

about:
  home: https://github.com/urineri/bbmapy
  license: MIT
  license_file: LICENSE
  summary: 'A Python wrapper for BBTools'
  description: |
    bbmapy is a Python wrapper for BBTools, a suite of bioinformatics tools.
    It provides a convenient interface to use BBTools from Python scripts.
  doc_url: https://github.com/urineri/bbmapy
  dev_url: https://github.com/urineri/bbmapy

extra:
  recipe-maintainers:
    - urineri 
